

version: "3.8"
services:
  allocation-app:
    build: .
    image: allocation-app:latest
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ./logs:/app/logs
      - ./outputs:/app/outputs
